//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosCliente
    {
        public int Id_Comentario { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Programa { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> Fecha_Comentario { get; set; }
    
        public virtual Programas Programas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
