//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrocinadores
    {
        public int Id_Patrocinador { get; set; }
        public string Nombre_Patrocinador { get; set; }
        public int Veces_Por_Dia { get; set; }
        public string Imagen_Ruta { get; set; }
        public string Url { get; set; }
    }
}
